INSERT INTO projects VALUES (1, "Mr", "bleh", "£10", "2/10/18", "NEVER");
INSERT INTO projects VALUES (2, "Mr", "bleh2", "£20", "3/8/17", "NEVER");
INSERT INTO projects VALUES(3, "Mrs", "bleh", "£50", "5/3/14", "NEVER");
INSERT INTO projects VALUES (4, "Mr", "bleh", "£10", "2/10/18", "NEVER");
INSERT INTO projects VALUES (5, "Mr", "bleh2", "£20", "3/8/17", "NEVER");
INSERT INTO projects VALUES(6, "Mrs", "bleh", "£50", "5/3/14", "NEVER");
INSERT INTO projects VALUES (7, "Mr", "bleh", "£10", "2/10/18", "NEVER");
INSERT INTO projects VALUES (8, "Mr", "bleh2", "£20", "3/8/17", "NEVER");
INSERT INTO projects VALUES(9, "Mrs", "bleh", "£50", "5/3/14", "NEVER");
INSERT INTO projects VALUES (10, "Mr", "bleh", "£10", "2/10/18", "NEVER");

INSERT INTO users VALUES (1, "James", "21");
INSERT INTO users VALUES (2, "John", "36");
INSERT INTO users VALUES(3, "Mary", "23");
INSERT INTO users VALUES (4, "James", "21");
INSERT INTO users VALUES (5, "John", "36");
INSERT INTO users VALUES(6, "Mary", "23");
INSERT INTO users VALUES (7, "James", "21");
INSERT INTO users VALUES (8, "John", "36");
INSERT INTO users VALUES(9, "Mary", "23");
INSERT INTO users VALUES (10, "James", "21");
INSERT INTO users VALUES (11, "John", "36");
INSERT INTO users VALUES(12, "Mary", "23");
INSERT INTO users VALUES (13, "James", "21");
INSERT INTO users VALUES (14, "John", "36");
INSERT INTO users VALUES(15, "Mary", "23");
INSERT INTO users VALUES (16, "James", "21");
INSERT INTO users VALUES (17, "John", "36");
INSERT INTO users VALUES(18, "Mary", "23");
INSERT INTO users VALUES (19, "James", "21");
INSERT INTO users VALUES (20, "John", "36");

INSERT INTO pledges VALUES (1, 7, 1, 1);
INSERT INTO pledges VALUES (2, 14, 2, 2);
INSERT INTO pledges VALUES(3, 18, 3, 3);